# -*- coding: utf-8 -*-
"""Chatbot NLP SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-yoPrUGGta4C77IO9ewadNQoXq42ZJDU
"""



!pip install googletrans==4.0.0-rc1

import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from fastapi import FastAPI
import joblib

df = pd.read_excel("/content/merged_chatbot_dataset.xlsx")

df.head()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s\u0600-\u06FF]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df["clean_text"] = df["example"].astype(str).apply(clean_text)

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["clean_text"])
y = df["intent"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = SVC(kernel="linear", probability=True)
model.fit(X_train, y_train)

def get_response(intent):
    intent_rows = df[df["intent"] == intent]

    arabic_response = None
    english_response = None
    for index, row in intent_rows.iterrows():
        response_text = str(row["response"]).strip()
        lang = str(row["language"]).strip().lower()

        if lang == "en":
            english_response = response_text
        elif lang == "ar":
            arabic_response = response_text


    if arabic_response is None and english_response is not None:
        try:
            arabic_response = translator.translate(english_response, src='en', dest='ar').text
        except Exception as e:
            arabic_response = "ترجمة غير متوفرة حالياً."

    return {
        "arabic": arabic_response,
        "english": english_response
    }

def bot_reply(user_msg):
    cleaned = clean_text(user_msg)
    vect = vectorizer.transform([cleaned])
    intent = model.predict(vect)[0]
    return get_response(intent)

reply = bot_reply("ايه افضل شركة اجهزة كهربائية؟")
print("AR:", reply["arabic"])
print("EN:", reply["english"])

y_pred = model.predict(X_test)

print(y_pred)

print(accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

app = FastAPI()

@app.post("/chat")
def chat(message: str):
    reply = bot_reply(message)
    return reply

!uvicorn main:app --reload